# Generated by Django 3.2.15 on 2022-10-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scores',
            field=models.CharField(default='', max_length=100),
        ),
    ]
